'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Slider} from '@/components/ui/slider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ArrowUpRight,ArrowRight,Plus,Check,MoveHorizontal} from 'lucide-react';
const projects=[['Appartement Croix-Rousse','68m² · rénovation complète · 8 sem · Lyon 4e','after'],['Cuisine Brotteaux','18m² · cuisine+agencement · 4 sem · Lyon 6e','kitchen'],['Maison Caluire','125m² · rénovation partielle · 10 sem · Caluire-et-Cuire','house']];
const services=[['Rénovation complète','De la conception à la réception, un seul interlocuteur du début à la fin.'],['Cuisine','Conception, agencement, électroménager intégré.'],['Salle de bain',"Plomberie, carrelage, douche à l'italienne."],['Agencement sur mesure',"Rangements, cloisons, optimisation d'espace."],['Peinture & finitions','Enduits, peintures, revêtements muraux.']];
const method=[['Visite','On vient chez vous, on regarde, on écoute.'],['Devis','Un chiffrage détaillé, sans surprise.'],['Préparation','Plans, choix des matériaux, planning.'],['Travaux','Chantier suivi, propre, tenu dans les délais.'],['Réception',"On fait le tour ensemble, rien n'est validé sans vous."]];
const quotes=[["Nous voulions ouvrir la cuisine sans perdre le caractère de l'appartement. Accompagnés du premier plan jusqu'à la réception.",'Camille R.','Appartement Croix-Rousse'],['Délais tenus, chantier propre, un seul interlocuteur du début à la fin.','Julien M.','Cuisine Brotteaux'],["Le rendu dépasse largement ce qu'on imaginait.",'Sophie & Marc D.','Maison Caluire']];
export default function Page(){const[menu,setMenu]=useState(false),[position,setPosition]=useState([50]),[contact,setContact]=useState(false),[sent,setSent]=useState(false);const open=()=>{setSent(false);setContact(true)};return <><a className="skip" href="#main">Aller au contenu</a><header><a className="logo" href="#" aria-label="Maison Trait Juste — accueil"><span>MAISON</span><strong>TRAIT JUSTE<span className="logo-dot">.</span></strong></a><nav className={menu?'open':''} aria-label="Navigation principale">{[['RÉALISATIONS','realisations'],['SERVICES','services'],['NOTRE MÉTHODE','methode'],['CONTACT','contact']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><Button className="button header-cta" onClick={open}>Parler de mon projet <ArrowUpRight/></Button><Button variant="ghost" className="menu" aria-expanded={menu} onClick={()=>setMenu(!menu)} aria-label={menu?'Fermer le menu':'Ouvrir le menu'}>{menu?'FERMER':'MENU'} <Plus className={menu?'rotated':''}/></Button></header><main id="main">
<section className="hero"><div className="hero-top"><div className="hero-copy"><p className="label">MAISON TRAIT JUSTE — LYON</p><h1>NOUS TRANSFORMONS LES LIEUX QUE VOUS HABITEZ.</h1><p className="hero-sub">Rénovation intérieure. Lyon & alentours.</p><div className="hero-actions"><Button className="button" onClick={open}>Parler de mon projet <ArrowUpRight/></Button><a className="text-link" href="#realisations">Voir nos réalisations <ArrowRight/></a></div></div><div className="hero-photo"><img src="/images/after.webp" alt="Appartement lyonnais rénové, cuisine ouverte et séjour lumineux" fetchPriority="high"/><span className="photo-caption">APPARTEMENT CROIX-ROUSSE · LYON 4e</span></div></div><div className="hero-foot"><span>DES ESPACES REPENSÉS. UN PROJET BIEN MENÉ.</span><a href="#avant-apres">LA TRANSFORMATION EN IMAGES <span>↓</span></a></div></section>
<section id="realisations" className="section projects"><div className="section-heading"><div><p className="label">01 / RÉALISATIONS</p><h2>Trois projets, trois façons d'habiter autrement.</h2></div><span className="side-note">LYON & ALENTOURS</span></div><div className="project-grid">{projects.map(([title,desc,img],i)=><article className="project" key={title}><div className="project-photo"><img src={'/images/'+img+'.webp'} alt={title} loading="lazy"/><span className="project-index">0{i+1}</span></div><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
<section id="avant-apres" className="section transformation"><div className="section-heading"><div><p className="label">02 / AVANT — APRÈS</p><h2>Le même appartement, avant et après</h2></div><p>Appartement Croix-Rousse, 68 m². Faites glisser pour voir la transformation.</p></div><div className="comparison"><img src="/images/after.webp" alt="Après rénovation : cuisine ouverte et lumière naturelle" loading="lazy"/><img className="before" src="/images/before.webp" alt="Avant rénovation : cuisine fermée et finitions vieillissantes" loading="lazy" style={{clipPath:`inset(0 ${100-position[0]}% 0 0)`}}/><span className="compare-label before-label">AVANT</span><span className="compare-label after-label">APRÈS</span><div className="divider" style={{left:position[0]+'%'}}><span><MoveHorizontal/></span></div><Slider ref={el=>{const thumb=el?.querySelector('[role="slider"]');thumb?.setAttribute('aria-label','Comparer avant et après');thumb?.setAttribute('aria-valuetext',`${position[0]} % avant rénovation`)}} className="compare-slider" min={0} max={100} step={1} value={position} onValueChange={setPosition} aria-label="Comparer avant et après" aria-valuetext={`${position[0]} % avant rénovation`}/></div><div className="compare-captions"><p><strong>AVANT</strong>Cuisine fermée, cloison centrale, lumière limitée, finitions vieillissantes.</p><p><strong>APRÈS</strong>Cuisine ouverte, cloison supprimée, mobilier sur mesure, lumière naturelle retrouvée.</p></div></section>
<section id="services" className="section services"><div className="services-intro"><p className="label">03 / SERVICES</p><h2>Votre intérieur.<br/>Notre métier.</h2><span className="section-number" aria-hidden="true">05</span><p className="label">EXPERTISES COMPLÉMENTAIRES</p></div><div className="service-list">{services.map(([title,text],i)=><article key={title}><span className="service-index">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section id="methode" className="section method"><div className="section-heading"><div><p className="label">04 / COMMENT ÇA SE PASSE</p><h2>Un cadre clair.<br/>À chaque étape.</h2></div></div><ol className="timeline">{method.map(([title,text],i)=><li key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
<section id="contact" className="section testimonials"><div className="section-heading"><div><p className="label">05 / TÉMOIGNAGES</p><h2>Ils y habitent.<br/>Ils en parlent.</h2></div></div><div className="quotes">{quotes.map(([quote,name,project])=><figure key={name}><span className="quote-mark" aria-hidden="true">“</span><blockquote>{quote}</blockquote><figcaption><strong>{name}</strong><span>{project}</span></figcaption></figure>)}</div><div className="trust"><div><strong>+120</strong>{' '}<span>projets réalisés</span></div><div><strong>12 ans</strong>{' '}<span>d'expérience</span></div><div><strong>4,9/5</strong>{' '}<span>avis clients</span></div>{['Garantie décennale','Interlocuteur unique','Devis détaillé'].map(t=><p key={t}><Check/>{t}</p>)}</div><div className="final-cta"><div><p className="label">PARLONS DE VOTRE INTÉRIEUR</p><h2>Vous avez un projet ?</h2><p>Décrivez-nous votre espace, nous revenons vers vous avec un premier retour sous 48h.</p></div><Button className="button" onClick={open}>Démarrer mon projet <ArrowUpRight/></Button></div></section>
</main><footer><a className="logo" href="#"><span>MAISON</span><strong>TRAIT JUSTE.</strong></a><p>Concept créé par Megahana — marque fictive à des fins de démonstration.</p><span className="label">LYON & ALENTOURS</span></footer><Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog"><DialogTitle>Parler de mon projet</DialogTitle><DialogDescription>Décrivez-nous votre espace.</DialogDescription><form onSubmit={e=>{e.preventDefault();setSent(true)}} onChange={()=>setSent(false)}><label htmlFor="name">Votre nom<Input id="name" name="name" autoComplete="name" required maxLength={100}/></label><label htmlFor="email">Votre e-mail<Input id="email" name="email" type="email" autoComplete="email" required maxLength={200}/></label><label htmlFor="project">Votre projet<Textarea id="project" name="project" required minLength={10} maxLength={5000} placeholder="Votre espace, vos envies, votre calendrier…"/></label><p className="demo-note">Formulaire de démonstration : aucun message n’est envoyé et aucune information n’est conservée.</p><Button type="submit" className="button">Démarrer mon projet <ArrowUpRight/></Button><p role="status">{sent?'Votre demande de démonstration est validée. Aucun message n’a été envoyé.':''}</p></form></DialogContent></Dialog></>}
